#==============================================================================
# vim: softtabstop=2 shiftwidth=2 expandtab fenc=utf-8 cc=81 tw=80
#==============================================================================
#
# DESCRIPTION: Base recipe template
#
#==============================================================================
---
# Load qemu checkpoint
checkpoint: qemu.yaml
# Loads some helpful aliases (this files are located in steps/aliases/ directory)
aliases: defaults.yaml

# Custom shell environement (this files are located in steps/env/ directory)
env:
  - bashrc
  - functions.sh

# Global variables use by Kameleon engine and the steps
global:
  root_password: kameleon
  # Distribution
  arch: x86_64
  hostname: kameleon-$$distrib

  ## System variables. Required by kameleon engine
  # Include specific steps
  include_steps:
    - $$distrib/$$release
    - $$distrib

  ## QEMU options
  qemu_enable_kvm: "$(egrep '(vmx|svm)' /proc/cpuinfo > /dev/null && echo true)"
  qemu_cpu: 2
  qemu_memory_size: 768
  qemu_monitor_socket: $$kameleon_cwd/qemu_monitor.socket
  qemu_ssh_port: 55423
  qemu_arch: $$arch
  qemu_image_size: 10G
  qemu_image_disk: $$kameleon_cwd/base_$$kameleon_recipe_name.qcow2
  qemu_pidfile: $$kameleon_cwd/qemu.pid

  # rootfs options
  disk_device: /dev/vda
  rootfs: /rootfs
  filesystem_type: ext4

  # appliance options
  image_disk: $$kameleon_cwd/base_$$kameleon_recipe_name
  image_format: qcow2
  # Allowed formats are: tar.gz, tar.bz2, tar.xz, tar.lzo, qcow, qcow2, qed, vdi, raw, vmdk
  appliance_formats: tar.xz
  appliance_filename: "$$kameleon_cwd/$${kameleon_recipe_name}"
  appliance_tar_excludes: >
    ./etc/fstab ./root/.bash_history ./root/kameleon_workdir ./root/.ssh
    ./var/tmp/* ./tmp/* ./var/log/* ./dev/* ./proc/* ./run/*
    ./sys/* ./root/.rpmdb ./boot/extlinux ./boot/grub ./boot/grub2

  ssh_config_file: $$kameleon_cwd/ssh_config
  out_context:
    cmd: ssh -F $$ssh_config_file $${kameleon_recipe_name} -t /bin/bash
    workdir: /root/kameleon_workdir
    proxy_cache: 10.0.2.2

  in_context:
    cmd: ssh -F $$ssh_config_file $${kameleon_recipe_name} -t /bin/bash
    workdir: /root/kameleon_workdir
    proxy_cache: 10.0.2.2

  kernel_args: "net.ifnames=0 console=tty0 console=ttyS0,115200n8 selinux=0"

# Bootstrap the new system and create the 'in_context'
bootstrap:
  - download_iso
  - prepare_disk
  - prepare_netinstall
  - autoinstall
  - prepare_appliance
  - start_qemu

# Install and configuration steps
setup:
  - enable_checkpoint
  - configure_system
  - clean_system

# Export the generated appliance in the format of your choice
export:
  - disable_checkpoint
  - save_appliance:
    - output_filename: $$appliance_filename
    - output_formats: $$appliance_formats
    - tar_compression_level: "9"
    - tar_excludes: $$appliance_tar_excludes
